<?php ob_start() ?>

<form class="form-horizontal col-sm-8" role="form" method="post" action="<?php print BASE_URL . 'checkout'; ?>">
    <fieldset>
        <legend>Perches Details</legend>

        <div class="form-group">
            <label for="ref_id" class="col-sm-2 control-label">Reference Id</label>
            <div class="col-sm-10">
                <input type="text" name="ref_id" class="form-control" required="required" value="<?php print $data['ref_id']; ?>">
            </div>
        </div>

        <div class="form-group">
            <label for="amount" class="col-sm-2 control-label">Amount</label>
            <div class="col-sm-3">
                <select name="currency" class="form-control" required="required">
                    <option value="">Please Select</option>
                    <?php
                        foreach ($data['currencies'] as $currency) {
                            print '<option value="' . $currency . '">' . $currency . '</option>';
                        }
                    ?>
                </select>
            </div>
            <div class="col-sm-7">
                <input type="number" name="amount" class="form-control" required="required">
            </div>
        </div>

        <div class="form-group">
            <label for="desc" class="col-sm-2 control-label">Description</label>
            <div class="col-sm-10">
                <input type="text" name="desc" class="form-control" required="required" placeholder="Description">
            </div>
        </div>

    </fieldset>
    <fieldset>
        <legend>Customer Details</legend>

        <div class="form-group">
            <label for="fname" class="col-sm-2 control-label">First Name</label>
            <div class="col-sm-10">
                <input type="text" name="fname" class="form-control" required="required" placeholder="First Name">
            </div>
        </div>
        <div class="form-group">
            <label for="lname" class="col-sm-2 control-label">Last Name</label>
            <div class="col-sm-10">
                <input type="text" name="lname" class="form-control" required="required" placeholder="Last Name">
            </div>
        </div>
        <div class="form-group">
            <label for="email" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
                <input type="email" name="email" class="form-control" required="required" placeholder="Email">
            </div>
        </div>
        <div class="form-group">
            <label for="tel" class="col-sm-2 control-label">Telephone</label>
            <div class="col-sm-10">
                <input type="tel" name="tel" class="form-control" required="required" placeholder="Telephone">
            </div>
        </div>
        <div class="form-group">
            <label for="address_1" class="col-sm-2 control-label">Address </label>
            <div class="col-sm-10">
                <input type="text" name="address_1" class="form-control" required="required" placeholder="Address">
            </div>
        </div>
        <div class="form-group">
            <label for="city" class="col-sm-2 control-label">City</label>
            <div class="col-sm-10">
                <input type="text" name="city" class="form-control" required="required" placeholder="City">
            </div>
        </div>
        <div class="form-group">
            <label for="country" class="col-sm-2 control-label">Country</label>
            <div class="col-sm-10">
                <input type="text" name="country" class="form-control" required="required" placeholder="Country">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" required="required"> I agree with <a href="index.php/terms" target="_blank">Terms and Conditions</a>
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Proceed To Pay</button>
            </div>
        </div>
    </fieldset>
</form>

<?php $content = ob_get_clean() ?>

<?php include 'layout.phtml'; ?>
