<?php
//http://works.dev/testvpc/index.php/processLkr?Title=PHP+VPC+3-Party&vpc_3DSXID=fMVN0w8nZprngxTzJ3wGNXR81s0%3D&vpc_3DSenrolled=N&vpc_AVSRequestCode=Z&vpc_AVSResultCode=Unsupported&vpc_AcqAVSRespCode=Unsupported&vpc_AcqCSCRespCode=N&vpc_AcqResponseCode=04&vpc_Amount=100&vpc_BatchNo=20141008&vpc_CSCResultCode=N&vpc_Card=VC&vpc_Command=pay&vpc_Locale=en&vpc_MerchTxnRef=SOME_PRIFIX_4096B0AB_5434D968&vpc_Merchant=109464156861&vpc_Message=Declined&vpc_OrderInfo=This+is+test+description&vpc_ReceiptNo=428117571885&vpc_SecureHash=0FC3DE11FD612596F3C436896D385134&vpc_TransactionNo=1100000015&vpc_TxnResponseCode=2&vpc_VerSecurityLevel=06&vpc_VerStatus=E&vpc_VerType=3DS&vpc_Version=1

$content = null;
?>

<?php include 'layout.phtml'; ?>