<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>VPC with Simple MVC</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    </head>
    <body>
        <header class="container">
            <a href="<?php print BASE_URL; ?>">
                <h1>VPC with Simple MVC</h1>
            </a>
        </header>
        <section class="container">
            <?php if (isset($data['error'])) : ?>
                <div class="alert alert-danger"><?php print $data['error']; ?></div>
            <?php endif; ?>
            <?php print $content; ?>
        </section>
        <footer class="container">

        </footer>
    </body>
</html>